version: '2'
services:
    smsbanking-app:
        image: smsbanking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smsbanking-mysql:3306/smsbanking?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smsbanking-mysql:
        extends:
            file: mysql.yml
            service: smsbanking-mysql
